name: Lino_app
description: "Lino"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^7.6.2
  get:
  english_words : ^4.0.0
  provider : ^6.0.0
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.3
  http: ^1.2.1
  google_maps_flutter: ^2.7.0
  dotenv: ^4.2.0
  flutter_speed_dial: ^7.0.0
  qr_code_scanner: ^1.0.1
  mobile_scanner: ^5.1.1



dev_dependencies:
  test: any
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  
  fonts: 
  - family: SimpleRonde
    fonts: 
    - asset: fonts/SimpleRonde-Regular.ttf
  
  
  assets: 
  - assets/logos/logo_with_bird.png
  - assets/logos/logo_without_bird.png
  - assets/croc_blanc.webp
  - assets/croc_noir.webp
  - assets/croc_rose.webp
  - assets/shreque.webp
  - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
