name: Run Backend Tests

on:
  push:
    paths:
      - 'backend/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Adjust to match your project's Node.js version

      - name: Install dependencies
        run: |
          cd backend
          npm install

      - name: Run tests
        run: |
          cd backend
          npx cross-env NODE_ENV=test TS_NODE_COMPILER_OPTIONS="{\"module\": \"commonjs\" }" jest --runInBand --forceExit src/tests/api.test.js

      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: backend/test-results
